import test from 'tape';
import parseISO from 'date-fns/parseISO';
import { CalendarItem, createCalendar, createVerticalCalendar } from './Calendar';

const data: CalendarItem<string>[] = [
  { start: parseISO('2019-04-10T08:30'), end: parseISO('2019-04-10T11:30'), value: 'A' },
  { start: parseISO('2019-04-12T08:30'), end: parseISO('2019-04-12T11:30'), value: 'B' },
  { start: parseISO('2019-04-10T15:30'), end: parseISO('2019-04-10T18:30'), value: 'C' },
  { start: parseISO('2019-04-15T12:00'), end: parseISO('2019-04-15T15:00'), value: 'D' },
  { start: parseISO('2019-04-10T08:30'), end: parseISO('2019-04-10T11:30'), value: 'E' },
];

test('createCalendar', t => {
  const calendar = createCalendar(data);
  t.equal(calendar.length, 6);
  t.deepLooseEqual(calendar[0].date, parseISO('2019-04-10'));
  t.equal(calendar[0].rows.length, 2);
  t.equal(calendar[0].rows[0].items.length, 2);
  t.equal(calendar[0].rows[0].items[0].value, 'A');
  t.equal(calendar[0].rows[0].items[1].value, 'C');
  t.equal(calendar[0].rows[1].items.length, 1);
  t.equal(calendar[0].rows[1].items[0].value, 'E');
  t.deepLooseEqual(calendar[1].date, parseISO('2019-04-11'));
  t.equal(calendar[1].rows.length, 1);
  t.equal(calendar[1].rows[0].items.length, 0);
  t.deepLooseEqual(calendar[2].date, parseISO('2019-04-12'));
  t.equal(calendar[2].rows.length, 1);
  t.equal(calendar[2].rows[0].items.length, 1);
  t.equal(calendar[2].rows[0].items[0].value, 'B');
  t.deepLooseEqual(calendar[3].date, parseISO('2019-04-13'));
  t.equal(calendar[3].rows.length, 1);
  t.equal(calendar[3].rows[0].items.length, 0);
  t.deepLooseEqual(calendar[4].date, parseISO('2019-04-14'));
  t.equal(calendar[4].rows.length, 1);
  t.equal(calendar[4].rows[0].items.length, 0);
  t.deepLooseEqual(calendar[5].date, parseISO('2019-04-15'));
  t.equal(calendar[5].rows.length, 1);
  t.equal(calendar[5].rows[0].items.length, 1);
  t.equal(calendar[5].rows[0].items[0].value, 'D');
  t.end();
});

test('createVerticalCalendar', t => {
  const calendar = createCalendar(data);
  const verticalCalendar = createVerticalCalendar(calendar, 8, 22, 0.5);
  t.equal(verticalCalendar.length, 28);
  t.equal(verticalCalendar[0].hour, 8);
  t.equal(verticalCalendar[0].values.length, 7);
  t.equal(verticalCalendar[0].values[0].span, 1);
  t.equal(verticalCalendar[0].values[0].value, undefined);
  t.equal(verticalCalendar[0].values[1].span, 1);
  t.equal(verticalCalendar[0].values[1].value, undefined);
  t.equal(verticalCalendar[0].values[2].span, 28);
  t.equal(verticalCalendar[0].values[2].value, undefined);
  t.equal(verticalCalendar[0].values[3].span, 1);
  t.equal(verticalCalendar[0].values[3].value, undefined);
  t.equal(verticalCalendar[0].values[4].span, 28);
  t.equal(verticalCalendar[0].values[4].value, undefined);
  t.equal(verticalCalendar[0].values[5].span, 28);
  t.equal(verticalCalendar[0].values[5].value, undefined);
  t.equal(verticalCalendar[0].values[6].span, 8);
  t.equal(verticalCalendar[0].values[6].value, undefined);
  t.equal(verticalCalendar[1].hour, 8.5);
  t.equal(verticalCalendar[1].values.length, 3);
  t.equal(verticalCalendar[1].values[0].span, 6);
  t.equal(verticalCalendar[1].values[0].value, 'A');
  t.equal(verticalCalendar[1].values[1].span, 6);
  t.equal(verticalCalendar[1].values[1].value, 'E');
  t.equal(verticalCalendar[1].values[2].span, 6);
  t.equal(verticalCalendar[1].values[2].value, 'B');
  t.equal(verticalCalendar[2].hour, 9);
  t.equal(verticalCalendar[2].values.length, 0);
  t.equal(verticalCalendar[3].hour, 9.5);
  t.equal(verticalCalendar[3].values.length, 0);
  t.equal(verticalCalendar[4].hour, 10);
  t.equal(verticalCalendar[4].values.length, 0);
  t.equal(verticalCalendar[5].hour, 10.5);
  t.equal(verticalCalendar[5].values.length, 0);
  t.equal(verticalCalendar[6].hour, 11);
  t.equal(verticalCalendar[6].values.length, 0);
  t.equal(verticalCalendar[7].hour, 11.5);
  t.equal(verticalCalendar[7].values.length, 3);
  t.equal(verticalCalendar[7].values[0].span, 8);
  t.equal(verticalCalendar[7].values[0].value, undefined);
  t.equal(verticalCalendar[7].values[1].span, 21);
  t.equal(verticalCalendar[7].values[1].value, undefined);
  t.equal(verticalCalendar[7].values[2].span, 21);
  t.equal(verticalCalendar[7].values[2].value, undefined);
  t.equal(verticalCalendar[8].hour, 12);
  t.equal(verticalCalendar[8].values.length, 1);
  t.equal(verticalCalendar[8].values[0].span, 6);
  t.equal(verticalCalendar[8].values[0].value, 'D');
  t.equal(verticalCalendar[9].hour, 12.5);
  t.equal(verticalCalendar[9].values.length, 0);
  t.equal(verticalCalendar[10].hour, 13);
  t.equal(verticalCalendar[10].values.length, 0);
  t.equal(verticalCalendar[11].hour, 13.5);
  t.equal(verticalCalendar[11].values.length, 0);
  t.equal(verticalCalendar[12].hour, 14);
  t.equal(verticalCalendar[12].values.length, 0);
  t.equal(verticalCalendar[13].hour, 14.5);
  t.equal(verticalCalendar[13].values.length, 0);
  t.equal(verticalCalendar[14].hour, 15);
  t.equal(verticalCalendar[14].values.length, 1);
  t.equal(verticalCalendar[14].values[0].span, 14);
  t.equal(verticalCalendar[14].values[0].value, undefined);
  t.equal(verticalCalendar[15].hour, 15.5);
  t.equal(verticalCalendar[15].values.length, 1);
  t.equal(verticalCalendar[15].values[0].span, 6);
  t.equal(verticalCalendar[15].values[0].value, 'C');
  t.equal(verticalCalendar[16].hour, 16);
  t.equal(verticalCalendar[16].values.length, 0);
  t.equal(verticalCalendar[17].hour, 16.5);
  t.equal(verticalCalendar[17].values.length, 0);
  t.equal(verticalCalendar[18].hour, 17);
  t.equal(verticalCalendar[18].values.length, 0);
  t.equal(verticalCalendar[19].hour, 17.5);
  t.equal(verticalCalendar[19].values.length, 0);
  t.equal(verticalCalendar[20].hour, 18);
  t.equal(verticalCalendar[20].values.length, 0);
  t.equal(verticalCalendar[21].hour, 18.5);
  t.equal(verticalCalendar[21].values.length, 1);
  t.equal(verticalCalendar[21].values[0].span, 7);
  t.equal(verticalCalendar[21].values[0].value, undefined);
  t.equal(verticalCalendar[22].hour, 19);
  t.equal(verticalCalendar[22].values.length, 0);
  t.equal(verticalCalendar[23].hour, 19.5);
  t.equal(verticalCalendar[23].values.length, 0);
  t.equal(verticalCalendar[24].hour, 20);
  t.equal(verticalCalendar[24].values.length, 0);
  t.equal(verticalCalendar[25].hour, 20.5);
  t.equal(verticalCalendar[25].values.length, 0);
  t.equal(verticalCalendar[26].hour, 21);
  t.equal(verticalCalendar[26].values.length, 0);
  t.equal(verticalCalendar[27].hour, 21.5);
  t.equal(verticalCalendar[27].values.length, 0);
  t.end();
});
